### ISSUE TITLE
OAuthError: The response type is not supported by the authorization server. 

### ISSUE THREAD

**Issue by emmanuelframos** [okta/samples-nodejs-express-4#59]
1 - Click on Login

2 - When redirected to http://localhost:3000/implicit/callback: 

OAuthError: The response type is not supported by the authorization server. Configured response types: [code].

**Comment by yimingsue** [comment]
Same error blocked me.
Do you have any update on this?

**Comment by emmanuelframos** [comment]
I moved to another library.

**Comment by aarongranick-okta** [comment]
I noticed that your app is using a redirect of `http://localhost:3000/implicit/callback`. This is the default callback for our SPA samples. I think it's likely that you used the SPA client id instead of the client id for a "standard" (server-side) web application.

This sample (express/nodejs) is meant to demonstrate auth with a "standard" web application using the authorization-code flow. The default callback for this app is `http://localhost:8080/authorization-code/callback` Be sure you are using this "standard" web app as the CLIENT_ID environment variable (or in the testenv file).

Using the wrong clientId can cause this error. The SPA_CLIENT_ID is used only by the resource-server sample
